// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace RestClientSDKLibrary.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// to returns all the task on db
    /// </summary>
    public partial class TasksResults
    {
        /// <summary>
        /// Initializes a new instance of the TasksResults class.
        /// </summary>
        public TasksResults() { }

        /// <summary>
        /// Initializes a new instance of the TasksResults class.
        /// </summary>
        public TasksResults(IList<TaskResult> tasks = default(IList<TaskResult>))
        {
            Tasks = tasks;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tasks")]
        public IList<TaskResult> Tasks { get; set; }

    }
}
